spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: 2.2

loans:
  message: "Welcome to EazyBank cards related qa apis"
  contactDetails:
    name: Rohit - QA Lead
    email: rohit@eazybank.com
  onCallNumber:
    - 7589648597
    - 5478965412